### ISSUE TITLE
How to create new preconfigured location

### ISSUE THREAD

**Issue by tdesvenain** [NOAA-ORR-ERD/WebGnomeAPI#3]
Is there a documentation describing how to create a preconfigured location ?
Are the json files format documented ?
How can we generate .cur files ? shio.txt files ?
I could contribute to documentation when this will be clear for me

**Comment by tdesvenain** [comment]
Hi, maybe this is not the right place to ask those questions. Where can i get this kind of information : is there for instance a developer mailing / list, a slack-gitter-or-like channel ?

**Comment by coconnor8** [comment]
Hello Thomas,
We generally recommend users start from scratch and create a save file
rather than a location file. The location files are made using our in house
hydrodynamic model that is not publicly available, and the wizard interface
is
not necessary. You can set up your own location using the custom location
option
on the WebGnome site. The best place to start is our online data server,
gnome.orr.noaa.gov/goods.
There you can find maps for the world and current and wind data from
publicly available models
in GNOME compatible format. If you are able to find data for your area of
interest you
can load in the pieces then save your model so you don't have to load
everything in each time.
If you are unable to find data on our data server you would need to find
hydrodynamic data
elsewhere and convert it to one of GNOME's file formats.
Let me know if you have any further questions.

Best regards,
Caitlin

**Comment by ChrisBarker-NOAA** [comment]
And yes, this is a fine place for this sort of question.

I suggest following Caitlin's advice, but if you let us know your use case, we can perhaps provide a bit more guidance. To answer your questions specifically:

> Is there a documentation describing how to create a preconfigured location ?

nope :-( -- those are generally done by us in-house, so we haven't really documented it. And it would only be useful for someone intending to run their own WebGNOME server -- is that your intent?

> Are the json files format documented ?

Not really, but they are generated by py_gnome, which underlies WebGNOME -- so we don't write them by hand, most are auto-generated by running WebGNOME or a python script with py_gnome.

> How can we generate .cur files ? shio.txt files ?

.cur files specify a current pattern, that can be scaled by a time series (like the tides). We generate those with our CATS model -- which we can make available, but is not well documented :-(

shio.txt files provide the tidal constituents to drive a tidal current. It is generated by our in-house tide program, SHIO, which we don't post on the web, but we can make available on request.

**Comment by bhlevca** [comment]
Hi, I know that this is an old thread but it is exactly on the subject I am interested in:

- Yes, I want to run my own WebGNOME server 
- Yes, I want to create my own location files, especially that they are not available in the areas I am interested in.

I have several hydrodynamic modelling frameworks that  I can use: Mike, Delft3D-FM, FVCOM

Therefore, I will repeat the question: Is there any documentation or at least some instructions about how a hydrodynamic model  can be used to generate location files?

I had an exchange of emails with Caitlin in 2017, but I have given up on the project because of lack of funding. Now we finally, have gotten the money and I am trying to build the technical requirements.  

Any help is appreciated. I will try to contact Caitlin through the email channel again.

**Comment by ChrisBarker-NOAA** [comment]
yes, you should be able to do all of this :-) I'm afraid it's not as well documented as we'd like, but:

All the code is here in this gitHub orgranization.

For running your own WebGNOME server, see:

https://github.com/NOAA-ORR-ERD/WebGnomeClient/blob/master/WebGNOMEStack.rst

Once you have the whole thing running, you'll need to set up your model -- It's usually best, for this use case, to use PyGNOME, and write a Python script that sets up and can run the model. That is documented here:

https://gnome.orr.noaa.gov/doc/pygnome/index.html

For a pre-setup location, take a look at:

https://github.com/NOAA-ORR-ERD/WebGnomeAPI/tree/master/location_files

I'm afraid it's not documented, but essentially what we hve there is a GNOME "save file" (really a directory), and some configuration files.

Ask here for help if/when you get that far :-)

**Comment by bhlevca** [comment]
Thanks for the reply. I already got help from Caitlin :-) 
The toughest part is to understand how to build the so called location files., which are now directories. I need to dive in the technical documentation that describes the file formats, especially the CUR files, with which I am not familiar, ahd fins away to convert outputs from hydrodynamic models into CUR files.

A step by step process on how to build an entire WebGNOME server would be nice. I found it challenging to put everything together  as these pieces are not documented how they interact.

**Comment by ChrisBarker-NOAA** [comment]
" ahd fins away to convert outputs from hydrodynamic models into CUR files."

CUR files are for when you have a current "pattern" that you want to scale with, e.g. tidal currents.

If you have a full blown hydrodynamic model, you may want to use netcdf.

**Comment by bhlevca** [comment]
I fixed the typos, but you got the idea :-)

> If you have a full blown hydrodynamic model, you may want to use netcdf.

This is a very valuable tip.  I will  use a bull blown hydrodynamic model.  Some, such as Delft3D -FM already output in NetCDF. 
I assume that your examples for location files have only CUR files for legacy reasons. 
I will apply on lakes where I don't have tidal currents and wind is more important. 

I intend to create a scripting framework  that will pull forecast data for inputs, (hopefully GOODS allows that), run the HD model periodically and dump the output in the WebGNOME directories. 

Do you have any location file example  that uses netcdf?  Or the use of netcdf is called something else?
Thanks

**Comment by ChrisBarker-NOAA** [comment]
take a look at the scripting docs:

https://gnome.orr.noaa.gov/doc/pygnome/index.html

But the distinction really is not file format, but which "Mover" you want to use.

For currents, GNOME support two general types of movers:

1) a full time and spatially dependent "grid" of velocities - typical output from a hydrodynamic model

2) a current pattern (spatially dependent currents) scaled by a time series -- tidal currents, winds, etc.

The Location files use (2) because we want them to be usable for any time, and often there is no operational model available for the region. So we develop a set of current patterns, and then can scale them off of winds, river flows, tidal current predictions, etc.

In order to use (1) in a location file, you need to have run a hydrodynamic model for teh time period you are interested in, and then you can point PyGNOME at the model results.

We are currently beginning development on a system to have WebGNOME automatically reach out to GOODS (or maybe other sources) to get the latest currents to drive the model -- but that won't be operational for a while. However, it would not be all that hard to write a single case, if you have model results to point to.

**Comment by bhlevca** [comment]
Chris, I really appreciate your help. 

In our case for the Great Lakes or any other lake for that matter I think that only #1 is a good choice 

> 1. a full time and spatially dependent "grid" of velocities - typical output from a hydrodynamic model

#2 assumes some patterns, which appear in  in coastal areas of the oceans

> we are currently beginning development on a system to have WebGNOME automatically reach out to GOODS (or maybe other sources) to get the latest currents to drive the model -- but that won't be operational for a while.

Funny, you just described my project in the above sentence. My plan is to create a script based framework that would do exactly what you describe: 

1. Extract data from GOODS, perhaps other sources (meteorology, radiation, etc) for the spatial region and time frame ( which can be historical and forecast or a combination)  
2. place extracted data as input data for the hydrodynamic model
3. start the simulation 
4. when simulation is finished copy/convert the output to the WevGNOME location file.

I hope that this can be automated to run periodically  

My question was if there is an example of using NetCDF Mover  in WebGnome, all I have managed to find were location file directories that have WND, CUR  and json files.  Thanks

**Comment by ChrisBarker-NOAA** [comment]
I"m not sure you want a Location File exactly in that case.

But anyway, WebGNOMe is entirely driven py PyGNOME -- in the PyGNOME docs and examples, you see netcdf files used.

-CHB

**Comment by ChrisBarker-NOAA** [comment]
Please reopen (Or make a new issue) if you have further questions.
