### ISSUE TITLE
ImportError: No module named WebgnomeFormatter

### ISSUE THREAD

**Issue by jjYukgm** [NOAA-ORR-ERD/WebGnomeAPI#5]
I install the package and do the pytest successfully.
While I try to run it with the command:
> pserve config-example.ini

I failed to execute and got the message:
> ImportError: No module named WebgnomeFormatter

**Comment by ChrisBarker-NOAA** [comment]
That's odd -- it's defined in webgnome_api/__init__.py

are you sure that you are running pserve in the same environment as webgnome_api is installed in?

Note that sometimes the tests will find the source code, rather than the installed version, so tests can pass even if the package is not properly installed.

@jay-hennen: any other ideas?

**Comment by jjYukgm** [comment]
I reinstalled the package again.
It runs sucessfully now.

**Comment by ChrisBarker-NOAA** [comment]
Thanks for the report.
